# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CSCI 2500 Computer Organization (Spring 2016)
email: jlapre+CompOrgS16 AT gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the course web site for CSCI 2500 Computer Organization for Spring 2016.
  This site will be the repository for all of the content needed for this course.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://RPI-CSCI-2500-2016-Spring.github.io" # the base hostname & protocol for your site
github_username:  laprej

# Build settings
kramdown:
  input: GFM
  hard_wrap: false
